package message

// Standard conversational roles.
const (
	RoleSystem    = "system"
	RoleUser      = "user"
	RoleAssistant = "assistant"
	RoleTool      = "tool"
)

// ToolFunction defines the invoked tool name and JSON string arguments.
type ToolFunction struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// ToolCall represents an individual tool invocation generated by a language model.
type ToolCall struct {
	Index    *int         `json:"index,omitempty"`
	ID       string       `json:"id"`
	Type     string       `json:"type"`
	Function ToolFunction `json:"function"`
}

// Message represents a single conversational turn in the reasoning thread.
type Message struct {
	Role              string     `json:"role"`
	Content           string     `json:"content,omitempty"`
	ReasoningContent  string     `json:"reasoning_content,omitempty"`
	ReasoningDuration float64    `json:"reasoning_duration,omitempty"`
	ToolCalls         []ToolCall `json:"tool_calls,omitempty"`
	Name              string     `json:"name,omitempty"`
	ToolCallID        string     `json:"tool_call_id,omitempty"`
	PromptTokens      int        `json:"prompt_tokens,omitempty"`
	CompletionTokens  int        `json:"completion_tokens,omitempty"`
}

// IsUser reports whether the message was authored by the user.
func (m Message) IsUser() bool {
	return m.Role == RoleUser
}

// IsAssistant reports whether the message was generated by the assistant.
func (m Message) IsAssistant() bool {
	return m.Role == RoleAssistant
}

// IsSystem reports whether the message contains system-level instructions.
func (m Message) IsSystem() bool {
	return m.Role == RoleSystem
}

// IsTool reports whether the message is a tool execution result.
func (m Message) IsTool() bool {
	return m.Role == RoleTool
}

// HasToolCalls reports whether the assistant requested any tool executions.
func (m Message) HasToolCalls() bool {
	return len(m.ToolCalls) > 0
}

// TotalTokens returns the sum of prompt and completion tokens for this turn.
func (m Message) TotalTokens() int {
	return m.PromptTokens + m.CompletionTokens
}

// NewUser creates a user message.
func NewUser(content string) Message {
	return Message{
		Role:    RoleUser,
		Content: content,
	}
}

// NewSystem creates a system instruction message.
func NewSystem(content string) Message {
	return Message{
		Role:    RoleSystem,
		Content: content,
	}
}

// NewAssistant creates an assistant message.
func NewAssistant(content string) Message {
	return Message{
		Role:    RoleAssistant,
		Content: content,
	}
}

// NewToolResult creates a tool result message.
func NewToolResult(toolCallID string, name string, content string) Message {
	return Message{
		Role:       RoleTool,
		ToolCallID: toolCallID,
		Name:       name,
		Content:    content,
	}
}
